### ISSUE TITLE
OS X installation requires xcode gui?

### ISSUE THREAD

**Issue by samclearman** [mateogianolio/nblas#9]
When I try to install nblas from NPM I get the following error.  
Does nblas really require xcode?

```warning Error running install script for optional dependency: "/Users/samclearman/project/node_modules/nblas: Command failed.
Exit code: 1
Command: node-gyp configure && node-gyp rebuild
Arguments:
Directory: /Users/samclearman/project/node_modules/nblas
Output:
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Traceback (most recent call last):
  File \"/Users/samclearman/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py\", line 16, in <module>
    sys.exit(gyp.script_main())
  File \"/Users/samclearman/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py\", line 545, in script_main
    return main(sys.argv[1:])
  File \"/Users/samclearman/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py\", line 538, in main
    return gyp_main(args)
  File \"/Users/samclearman/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py\", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File \"/Users/samclearman/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py\", line 2170, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File \"/Users/samclearman/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py\", line 795, in Write
    self.Pchify))
  File \"/Users/samclearman/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py\", line 1190, in WriteSources
    cflags = self.xcode_settings.GetCflags(configname)
  File \"/Users/samclearman/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py\", line 551, in GetCflags
    archs = self.GetActiveArchs(self.configname)
  File \"/Users/samclearman/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py\", line 420, in GetActiveArchs
    xcode_archs_default = GetXcodeArchsDefault()
  File \"/Users/samclearman/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py\", line 118, in GetXcodeArchsDefault
    xcode_version, _ = XcodeVersion()
  File \"/Users/samclearman/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py\", line 1265, in XcodeVersion
    version = re.match(r'(\\d\\.\\d\\.?\\d*)', version).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/samclearman/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command \"/Users/samclearman/.nvm/versions/node/v8.9.3/bin/node\" \"/Users/samclearman/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"configure\"
gyp ERR! cwd /Users/samclearman/project/node_modules/nblas```

**Comment by mateogianolio** [comment]
It requires xcode command line tools, not xcode itself. You can install it by running:

```
xcode-select --install
```

**Comment by samclearman** [comment]
@mateogianolio I have xcode command line tools installed.  The output above includes the line `xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance`

**Comment by mateogianolio** [comment]
Hmm, which version of OSX are you on? I just tried installing node 8.9.3 (the version you're using) and installing nblas. I don't have xcode installed. Here's the output:

```
$ npm i nblas                                                                                  [19:35:14]

> nblas@1.2.2 install /Users/magi/projects/javascript/test_nblas/node_modules/nblas
> node-gyp configure && node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/addon/addon.o
  CXX(target) Release/obj.target/addon/routines/level1/asum.o
  CXX(target) Release/obj.target/addon/routines/level1/axpy.o
  CXX(target) Release/obj.target/addon/routines/level1/copy.o
  CXX(target) Release/obj.target/addon/routines/level1/dot.o
  CXX(target) Release/obj.target/addon/routines/level1/sdot.o
  CXX(target) Release/obj.target/addon/routines/level1/nrm2.o
  CXX(target) Release/obj.target/addon/routines/level1/rot.o
  CXX(target) Release/obj.target/addon/routines/level1/rotg.o
  CXX(target) Release/obj.target/addon/routines/level1/rotm.o
  CXX(target) Release/obj.target/addon/routines/level1/rotmg.o
  CXX(target) Release/obj.target/addon/routines/level1/scal.o
  CXX(target) Release/obj.target/addon/routines/level1/swap.o
  CXX(target) Release/obj.target/addon/routines/level1/iamax.o
  CXX(target) Release/obj.target/addon/routines/level2/gbmv.o
  CXX(target) Release/obj.target/addon/routines/level2/gemv.o
  CXX(target) Release/obj.target/addon/routines/level2/ger.o
  CXX(target) Release/obj.target/addon/routines/level2/sbmv.o
  CXX(target) Release/obj.target/addon/routines/level2/spmv.o
  CXX(target) Release/obj.target/addon/routines/level2/spr.o
  CXX(target) Release/obj.target/addon/routines/level2/spr2.o
  CXX(target) Release/obj.target/addon/routines/level2/symv.o
  CXX(target) Release/obj.target/addon/routines/level2/syr.o
  CXX(target) Release/obj.target/addon/routines/level2/syr2.o
  CXX(target) Release/obj.target/addon/routines/level2/tbmv.o
  CXX(target) Release/obj.target/addon/routines/level2/tbsv.o
  CXX(target) Release/obj.target/addon/routines/level2/tpmv.o
  CXX(target) Release/obj.target/addon/routines/level2/tpsv.o
  CXX(target) Release/obj.target/addon/routines/level2/trmv.o
  CXX(target) Release/obj.target/addon/routines/level2/trsv.o
  CXX(target) Release/obj.target/addon/routines/level3/gemm.o
  CXX(target) Release/obj.target/addon/routines/level3/symm.o
  CXX(target) Release/obj.target/addon/routines/level3/syrk.o
  CXX(target) Release/obj.target/addon/routines/level3/syr2k.o
  CXX(target) Release/obj.target/addon/routines/level3/trmm.o
  CXX(target) Release/obj.target/addon/routines/level3/trsm.o
  SOLINK_MODULE(target) Release/addon.node
npm WARN saveError ENOENT: no such file or directory, open '/Users/magi/projects/javascript/test_nblas/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/magi/projects/javascript/test_nblas/package.json'
npm WARN test_nblas No description
npm WARN test_nblas No repository field.
npm WARN test_nblas No README data
npm WARN test_nblas No license field.

+ nblas@1.2.2
added 1 package in 43.315s
```

**Comment by samclearman** [comment]
OS version is 10.13.4.

Yeah those 'requires xcode' warnings do seem to happen spuriously but in my case the actual error I get sure seems to be related to xcode...

Looking at my software update history I see that command line tools version 10.0 beta 1 installed itself on June 5, maybe that's related?

**Comment by mateogianolio** [comment]
Might be... I will try upgrading OSX and then get back to you with installation results. Which version of npm are you on?

**Comment by samclearman** [comment]
5.5.1

**Comment by mateogianolio** [comment]
Hmm it seems we had a previous build issue that was caused by nvm (see #2). Could you try installing without nvm and see if it makes any difference?

**Comment by samclearman** [comment]
Tried it without nvm, this time using node 8.11.3, still getting the same error

**Comment by samclearman** [comment]
This was a node-gyp issue which has been resolved.
